mutation UpdateAttendanceCheckOut(
    $id: UUID!
    $checkOut: Timestamp!
) @auth(level: USER) {
    attendance_update(
        id: $id
        data: {
            checkOut: $checkOut
        }
    )
}