extend type Career {
  """
  ✨ List `Student` objects in a one-to-many relationship (where `Student`.`career` is this object).
  """
  students_on_career(
    """
    Filter condition to narrow down the query results.
    """
    where: Student_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Student_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Student_Having
  ): [Student!]! @fdc_generated(from: "Student.career", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Career", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Career` table.
  """
  _count: Int! @fdc_generated(from: "Career.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Career` table where the `departmentId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  departmentId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Career.departmentId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Career` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Career.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Career` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Career.name", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Career.id", purpose: ENTITY_ID)
}
extend type Department {
  """
  ✨ List `Career` objects in a one-to-many relationship (where `Career`.`department` is this object).
  """
  careers_on_department(
    """
    Filter condition to narrow down the query results.
    """
    where: Career_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Career_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Career_Having
  ): [Career!]! @fdc_generated(from: "Career.department", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Department", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Department` table.
  """
  _count: Int! @fdc_generated(from: "Department.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Department` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Department.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Department` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Department.name", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Department.id", purpose: ENTITY_ID)
}
extend type Role {
  """
  ✨ List `User` objects in a one-to-many relationship (where `User`.`role` is this object).
  """
  users_on_role(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User.role", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Role", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Role` table.
  """
  _count: Int! @fdc_generated(from: "Role.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Role` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Role.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Role` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Role.name", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Role.id", purpose: ENTITY_ID)
}
extend type Student {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Student", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Student` table.
  """
  _count: Int! @fdc_generated(from: "Student.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Student` table where the `birthDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  birthDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Student.birthDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Student` table where the `careerId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  careerId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Student.careerId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Student` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Student.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Student` table where the `phoneNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phoneNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Student.phoneNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Student` table where the `studentCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  studentCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Student.studentCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Student` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Student.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `birthDate` field in the `Student` table.
  """
  birthDate_min: Date @fdc_generated(from: "Student.birthDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `birthDate` field in the `Student` table.
  """
  birthDate_max: Date @fdc_generated(from: "Student.birthDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Student.id", purpose: ENTITY_ID)
}
extend type User {
  """
  ✨ List `Student` objects in a one-to-one relationship (where `Student`.`user` is this object).
  """
  student_on_user: Student @fdc_generated(from: "Student.user", purpose: QUERY_SINGLE_ONE_TO_ONE)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `fullName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fullName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.fullName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `isActive` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isActive_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.isActive", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `photoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  photoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.photoUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `roleId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  roleId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.roleId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Date @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Date @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: ENTITY_ID)
}
