query GetUserById($id: String!) @auth(level: USER) {
    users(where: {id: {eq: $id}}) {
        id
        email
        fullName
        photoUrl
        isActive
        role{
            id
            name
        }
    }
}

mutation CreateUser (
    $id: String!
    $email: String!
    $fullName: String!
    $photoUrl: String!
    $roleId: UUID!
) @auth(level: USER){
    user_insert(data: {
        id: $id
        email: $email
        fullName: $fullName
        photoUrl: $photoUrl
        roleId: $roleId
    })
}

mutation CreateStudent(
    $studentCode: String!
    $phoneNumber: String!
    $birthDate: Date
    $userId: String!
    $careerId: UUID
) @auth(level: USER){
    student_insert(data: {
        studentCode: $studentCode
        phoneNumber: $phoneNumber
        birthDate: $birthDate
        userId: $userId
        careerId: $careerId
    })
}

