type Role @table {
  id: UUID! @default(expr: "uuidV4()")
  name: String! @unique
}


type Department @table {
  id: UUID! @default(expr: "uuidV4()")
  name: String! @unique
}

type Career @table {
  id: UUID! @default(expr: "uuidV4()")
  name: String!@unique
  department: Department!
}

type  User @table {
  #Firebase UID
  id: String! @default(expr: "auth.uid")
  email: String! @unique
  fullName: String!
  photoUrl:String
  isActive: Boolean! @default(value: true)
  createdAt: Date! @default(expr: "request.time")
  role: Role!
}

type Student @table {
  id: UUID! @default (expr: "uuidV4()")
  studentCode: String! @unique
  phoneNumber: String
  birthDate: Date
  user: User! @unique
  career: Career
}

type ProjectType @table {
  id: UUID! @default(expr: "uuidV4()")
  name: String! @unique
}

type Project @table {
  id: UUID! @default(expr: "uuidV4()")
  name: String!
  description: String
  projectType: ProjectType!
  supervisor: User!
  startDate: Date!
  endDate: Date!
  latitude: Float!
  longitude: Float!
  allowedRadius: Float!
  maxStudents: Int!
  maxHoursPerDay: Int! @default(value: 5)
  totalRequiredHours: Int!
  isActive: Boolean! @default(value: false)
  createdAt: Date!  @default(expr:"request.time")
}

type ProjectCareer @table (key: ["project", "career"]){
  project: Project!
  career: Career!
}

type ProjectSchedule @table {
  id: UUID!  @default(expr: "uuidV4()")
  participant: Participant!
  dayOfWeek: Int!
  startHour: String!
  endHour: String!
}

type Participant @table {
  id:  UUID! @default(expr: "uuidV4()")
  student: Student!
  project: Project!
  status: String!
  accumulateHours: Float! @default(value: 0)
  registeredAt: Date! @default(expr:"request.time")
}

type Attendance @table {
  id: UUID! @default(expr:"uuidV4()")
  participant: Participant!
  checkIn: Timestamp!
  checkOut: Timestamp
  latitude: Float!
  longitude: Float!
  status: String!
}

type Activity @table {
  id: UUID! @default(expr:"uuidV4()")
  attendance: Attendance!
  title: String!
  description: String!
  approved:Boolean! @default(value: false)
  createdAt:  Date! @default(expr:"request.time")
}